name: Nodejs build Template
on:
  workflow_call:
    inputs:
     node-version:
      required: true
      type: string
      description: 'The nodejs version to use for the build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ input.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        run: npm install
